name: build

on:
  push:
    branches:
      - release/**

jobs:
  dist:
    name: distribution packages
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - run: |
          pip install wheel
          python setup.py bdist_wheel
      - uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ github.sha }}
          path: dist/*
