name: Test
on:
  push:
    branches:
      - "main"
      - "releases/**"
  pull_request:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11", "3.12"]
    name: "test (Python ${{ matrix.python-version }})"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Tox
        run: pip install tox
      - name: Run Tests
        run: tox -e py
